[package]
name = "myruststudio"
version = "0.1.0"
edition = "2024"

[dependencies]
dyn-clone = "1.0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.0"
serde_closure = "0.3.3"
md5 = "0.7.0"
aes = "0.8.4"
hex-literal = "0.4.1"
ecb = "0.1.2"
hex = "0.4.3"
tracing="0.1"

tracing-error = "0.2"
tracing-subscriber = { version = "0.3", features = ["std", "local-time"] }
tracing-appender = "0.2"
# rand_chacha = "0.3.1"
rand_aes = "0.3.1"
rand = {version = "0.8.5", features = ["std"]}
rand_core = "0.9.3" 
# { version = "0.9.3", default-features = false }
anyhow = "1.0.80"
# aes = "0.8.4"
cbc = { version = "0.1.2", features = ["alloc"] }

rsa = "0.10.0-rc.5"
# sha2 = "0.10.8"
sha2="0.11.0-rc.0"
# sha2 = { version = "0.11.0-rc.0", optional = true, default-features = false, features = ["oid"] }
# rand_chacha = "0.3.1"
rand_chacha = "0.9"
sha1 = "0.10.6"

crypto-bigint = { version = "0.7.0-rc.2", default-features = false, features = ["zeroize", "alloc"] }
base64ct = { version = "1", features = ["alloc"] }
markdown2pdf="0.1"
# html2md = "0.2.15"
fast_html2md = "0.0.62"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
num_threads = "0.1.7"
thread-amount = "0.3.0"
num_cpus = "1.17.0"
thread-control = "0.1.2"
thread-priority = "3.0.0"
crossbeam = "0.8.4"
crossbeam-thread = "0.0.0"
rayon = "1.12.0"
send_wrapper = "0.6.0"
go-spawn = "0.1.2"
scoped-tls = "1.0.1"
threadpool = "1.8.1"
rusty_pool = "0.7.0"
fast-threadpool = "0.3.0"
scoped_threadpool = "0.1.9"
scheduled-thread-pool = "0.2.7"
poolite = "0.7.1"
executor-service = "0.2.2"
threadpool-executor = "0.3.3"
# affinity = "0.1.2"
futures = { version = "0.3.32", features = ["thread-pool"] }
futures-lite = "2.6.1"
async-std = "1.13.2"
smol = "2.0.2"
beef = "0.5.2"
once_cell = "1.21.4"
dashmap = "6.2.1"
cuckoofilter = "0.5.0"
evmap = "11.0.0"
arc-swap = "1.9.1"
nix ={ version = "0.31.3",features = ["process","fs"]}
crossbeam-channel = "0.5.15"
flume = "0.12.0"
crossfire = "3.1.16"
async-channel = "2.5.0"
futures-channel = "0.3.32"
kanal = "0.1.1"
futures-timer = "3.0.4"
async-io = "2.6.0"
async-timer = "0.7.4"

timer-kit = { version = "0.1.1", features = ["tokio", "smol"] }
hierarchical_hash_wheel_timer = { version = "1.4.0", features = ["fx-hash"] }
timer = "0.2.0"
chrono = "0.4.45"
ticker = "0.1.1"
uuid = "1.23.3"
parking_lot = "0.12.5"
crossbeam-deque = "0.8.6"
crossbeam-queue = "0.3.12"
crossbeam-utils = "0.8.21"
crossbeam-skiplist = "0.1.3"
process_lock = "0.1.0"
oneshot = "0.2.1"
async-lock = "3.4.2"
waitgroup = "0.1.2"
wg = "1.0.1"
event-listener = "5.4.1"
concurrent-queue = "2.5.0"
scc = "3.7.3"
async-weighted-semaphore = "0.2.1"
singleflight-async = "0.2.0"
named-lock = "0.4.1"
async-oneshot = "0.5.9"
catty = "0.1.5"
flurry = "0.5.2"
awaitgroup = "0.7.0"
triggered = "0.1.3"
barrage = "0.2.3"
[[example]]
name="enumfn"
path="src/enumfn.rs"
[[example]]
name="test"
path="src/fnpointer.rs"

[[example]]
name="rsa"
path="src/crypto/rust_crypto_demo/main.rs"


[[example]]
name="oaep"
path="src/crypto/rust_crypto_demo/main1.rs"
[[example]]
name="const"
path="src/const/const5.rs"

[[example]]
name="h2md"
path="src/html2md.rs"
[[example]]
name="con"
path="src/concurrency/timer/timer.rs"
